[build]
builder = "nixpacks"
buildCommand = "go build -o bin/server ./cmd"

[deploy]
startCommand = "./bin/server"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 300